name: frappe_dart_api_client
version: 1.0.0
description: Frappe - nexterp - flutter API client
authors:
  - Author <alvaro@irradia.io>
homepage: https://irradia.io
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  http: '>=0.12.0 <0.13.0'
dev_dependencies:
  test: ^1.3.0
